#!/bin/bash
# set -e

platforms=("linux/amd64" "linux/arm64")


for platform in "${platforms[@]}"
do

  image="${1:-pactfoundation/pact-broker-cli}"
  tag="${2:-latest}"
  echo "Running $image:$tag on $platform"
  docker run --rm --platform "$platform" "$image:$tag"
  # docker run --rm --init  -e PACT_BROKER_DATABASE_URL=sqlite:////tmp/pact_broker.sqlite --platform "$platform" "$image:$tag"
done
