name: Docker Builder

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the pact cli to release as'
        default: 'latest'

jobs:

  cli_docker:
    runs-on: ubuntu-latest
    permissions: ## needed to publish images to ghcr.io
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Docker Images
        run: hooks/build
        working-directory: ./docker
        env:
          DOCKER_TAG: ${{ github.event.inputs.version }}
          PUSH_IMAGE: true
