name: Record Deployment

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  record-deployment:
    name: Record Deployment in PactFlow
    runs-on: ubuntu-latest
    env:
      PACTICIPANT: pact-broker-cli
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: ./
      - name: Record deployment
        env:
          PLAN: ${{ inputs.plan }}
          PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_PACT_OSS_TOKEN }}
        run: |
          pact-broker-cli record-deployment \
            --pacticipant "${PACTICIPANT}" \
            --version "${GITHUB_SHA}" \
            --application-instance "$(echo "$PLAN" | jq -r '.announcement_tag')" \
            --environment production
